### ISSUE TITLE
Add sphinx module

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/github-actions-base#33]
## 💡 Description

For pds-api build to work (see action https://github.com/NASA-PDS/pds-api/actions/runs/4735783155/jobs/8406453520)
 We need the module `sphinx_substitution_extensions` to be added.

**Comment by tloubrieu-jpl** [comment]
@nutjob4life the github action still fails with the same error: https://github.com/NASA-PDS/pds-api/actions/runs/4885019123/jobs/8718534082

**Comment by nutjob4life** [comment]
@tloubrieu-jpl this is becoming a dependency nightmare:

- `sphinx_substitution_extensions==2020.5.27.0` downgrades Sphinx from 3.2.1 → 3.0.4, which isn't ideal but at least is okay for now
- The next version up, `sphinx_substitution_extensions==2020.5.30.0` _upgrades_ Sphinx 3.2.1 → 6.2.1, which is totally unacceptable due to jinja2 conflicts
- The `conf.py` in `pds-api` is missing `sphinx-prompt`
- But adding `sphinx-prompt` then requires `sphinx-copybutton==0.5.2` in `github-actions-base`

If we break up `pds-github-util` then all of this goes away because each repository can specify its own custom sphinx. (It would be better to spend my limited time on PDS on that!)

I'll have PRs ready to address these issues shortly.

**Comment by nutjob4life** [comment]
PRs are filed. Note the following must happen:

- [x] [PR against pds-api](https://github.com/NASA-PDS/pds-api/pull/264) must be merged
- [x] [PR against github-actions-base](https://github.com/NASA-PDS/github-actions-base/pull/35) must be merged
- [x] New `:stable` tag of the github-actions-base image in the Docker hub must be tagged after the second PR is merged and the new `:latest` image is published

**Comment by tloubrieu-jpl** [comment]
Thanks @nutjob4life , I think I already broke what you done by upgrading sphynx in the pds-api repo (because I was not able to generate the documentation locally anymore). Hopefull when I'll go across that again at the end of next build, pds-github-util will be broken up.
